/**
 * Pure lyrics-block logic, kept out of components so it can be unit tested
 * without rendering React.
 */

/**
 * Compiles lyric blocks into the sequence that gets sent to Suno.
 *
 * Chorus repetition is no longer a compile-time transform - see
 * `repeatChorusAfterVerses`, which materializes real chorus blocks into the
 * stored block list instead. This is now a plain `{ type, content }` mapper
 * so callers can apply their own type-label translation before joining.
 */
export function compileLyrics(blocks) {
  return blocks.map((b) => ({ type: b.type, content: b.content }));
}

export function formatLyrics(segments, typeLabel) {
  return segments.map((s) => `[${typeLabel(s.type)}]\n${s.content}`).join('\n\n');
}

/**
 * Splits the block with `id` into two blocks at `lineIndex` (the number of
 * lines that stay in the first half). Both halves keep the original block's
 * type and importance - the user re-tags them via the type picker instead of
 * typing. `newId` is generated by the caller so this stays pure/testable.
 * No-op if `id` isn't found or `lineIndex` doesn't fall strictly inside the
 * block's lines.
 */
export function splitBlockAtLine(blocks, id, lineIndex, newId) {
  const idx = blocks.findIndex((b) => b.id === id);
  if (idx === -1) return blocks;
  const lines = blocks[idx].content.split('\n');
  if (lineIndex <= 0 || lineIndex >= lines.length) return blocks;

  const first = { ...blocks[idx], content: lines.slice(0, lineIndex).join('\n') };
  const second = { ...blocks[idx], id: newId, content: lines.slice(lineIndex).join('\n') };
  const arr = [...blocks];
  arr.splice(idx, 1, first, second);
  return arr;
}

/** Moves the block with `id` by `direction` (-1 or 1) places, clamped to array bounds. */
export function moveBlock(blocks, id, direction) {
  const idx = blocks.findIndex((b) => b.id === id);
  if (idx === -1) return blocks;
  const to = idx + direction;
  if (to < 0 || to >= blocks.length) return blocks;
  const arr = [...blocks];
  [arr[idx], arr[to]] = [arr[to], arr[idx]];
  return arr;
}

/**
 * Toggles round-bracket wrapping on one line of a block's `\n`-joined
 * `content`. If the line is already wrapped (trimmed form starts with `(`
 * and ends with `)`), the wrapping is removed; otherwise the raw line gets
 * wrapped. No-op if `lineIndex` is out of range.
 */
export function toggleLineBrackets(content, lineIndex) {
  const lines = content.split('\n');
  if (lineIndex < 0 || lineIndex >= lines.length) return content;
  const line = lines[lineIndex];
  const trimmed = line.trim();
  if (trimmed.length >= 2 && trimmed.startsWith('(') && trimmed.endsWith(')')) {
    const start = line.indexOf('(');
    const end = line.lastIndexOf(')');
    lines[lineIndex] = line.slice(0, start) + line.slice(start + 1, end) + line.slice(end + 1);
  } else {
    lines[lineIndex] = `(${line})`;
  }
  return lines.join('\n');
}

/**
 * Moves the block with `id` to the very start (`'start'`) or end (`'end'`)
 * of the array. No-op if `id` isn't found or `edge` is unrecognized.
 */
export function moveBlockToEdge(blocks, id, edge) {
  if (edge !== 'start' && edge !== 'end') return blocks;
  const idx = blocks.findIndex((b) => b.id === id);
  if (idx === -1) return blocks;
  const arr = [...blocks];
  const [block] = arr.splice(idx, 1);
  if (edge === 'start') arr.unshift(block);
  else arr.push(block);
  return arr;
}

/**
 * Moves the block with `id` to the start of the array if `type` is `'intro'`,
 * or to the end if `type` is `'outro'`. No-op for any other type or if `id`
 * isn't found.
 */
export function moveToEdgeForType(blocks, id, type) {
  if (type === 'intro') return moveBlockToEdge(blocks, id, 'start');
  if (type === 'outro') return moveBlockToEdge(blocks, id, 'end');
  return blocks;
}

/**
 * Duplicates the block with `id` right after itself, assigning `newType` to
 * the clone only - the original block is untouched. If the clone's type is
 * `intro`/`outro` it then jumps to the matching edge, per
 * `moveToEdgeForType`. `newId` is generated by the caller. No-op if `id`
 * isn't found.
 */
export function cloneBlockWithType(blocks, id, newType, newId) {
  const idx = blocks.findIndex((b) => b.id === id);
  if (idx === -1) return blocks;
  const clone = { ...blocks[idx], id: newId, type: newType };
  const arr = [...blocks];
  arr.splice(idx + 1, 0, clone);
  return moveToEdgeForType(arr, newId, newType);
}

/**
 * One-shot action: inserts a clone of the first `chorus` block after every
 * `verse` block in the array (existing blocks, including the original
 * chorus, keep their positions). No-op if there's no chorus or no verse
 * block. Not idempotent - calling this twice inserts two sets of clones.
 * `idGenerator` is called once per inserted clone.
 */
export function repeatChorusAfterVerses(blocks, idGenerator) {
  const chorus = blocks.find((b) => b.type === 'chorus');
  const hasVerse = blocks.some((b) => b.type === 'verse');
  if (!chorus || !hasVerse) return blocks;

  const out = [];
  for (const b of blocks) {
    out.push(b);
    if (b.type === 'verse') out.push({ ...chorus, id: idGenerator(), type: 'chorus' });
  }
  return out;
}

/**
 * Splits the block with `id` into consecutive groups of `n` lines each (the
 * last group may be shorter), replacing the one block with the resulting
 * blocks in place. All resulting blocks keep the original block's
 * type/importance; the first keeps the original `id`, the rest get ids from
 * `idGenerator`. No-op if `id` isn't found or `n < 2`.
 */
export function splitBlockEveryN(blocks, id, n, idGenerator) {
  const idx = blocks.findIndex((b) => b.id === id);
  if (idx === -1 || n < 2) return blocks;
  const lines = blocks[idx].content.split('\n');
  const chunks = [];
  for (let i = 0; i < lines.length; i += n) chunks.push(lines.slice(i, i + n));

  const newBlocks = chunks.map((chunk, i) => ({
    ...blocks[idx],
    id: i === 0 ? blocks[idx].id : idGenerator(),
    content: chunk.join('\n'),
  }));
  const arr = [...blocks];
  arr.splice(idx, 1, ...newBlocks);
  return arr;
}

/**
 * Inserts a new block (`type`/`content`, default `importance: 3`) immediately
 * before or after the block with `id`, per `position` (`'before'`|`'after'`).
 * `newId` is generated by the caller. No-op if `id` isn't found.
 */
export function insertBlockAdjacent(blocks, id, type, content, position, newId) {
  const idx = blocks.findIndex((b) => b.id === id);
  if (idx === -1) return blocks;
  const block = { id: newId, type, content, importance: 3 };
  const arr = [...blocks];
  arr.splice(position === 'before' ? idx : idx + 1, 0, block);
  return arr;
}
