/**
 * Pure lyrics-block logic, kept out of components so it can be unit tested
 * without rendering React.
 */

/**
 * Compiles lyric blocks into the sequence that gets sent to Suno.
 *
 * Per the spec's "Chorus Logic" (docs/specs/spec2.md, 2.2): when
 * `autoRepeatChorus` is on, the chorus block is virtually duplicated and
 * inserted after every verse block, in addition to wherever it already sits
 * in the block order. The stored block list itself is never mutated - this
 * only affects the compiled sequence.
 *
 * Returns an array of `{ type, content }` segments (not a formatted string),
 * so callers can apply their own type-label translation before joining.
 */
export function compileLyrics(blocks, autoRepeatChorus) {
  const plain = blocks.map((b) => ({ type: b.type, content: b.content }));
  if (!autoRepeatChorus) return plain;

  const chorus = blocks.find((b) => b.type === 'chorus');
  const hasVerse = blocks.some((b) => b.type === 'verse');
  if (!chorus || !hasVerse) return plain;

  const out = [];
  for (const b of blocks) {
    if (b.type === 'chorus') continue; // re-inserted after each verse instead
    out.push({ type: b.type, content: b.content });
    if (b.type === 'verse') out.push({ type: 'chorus', content: chorus.content });
  }
  return out;
}

export function formatLyrics(segments, typeLabel) {
  return segments.map((s) => `[${typeLabel(s.type)}]\n${s.content}`).join('\n\n');
}

/**
 * Splits the block with `id` into two blocks at `lineIndex` (the number of
 * lines that stay in the first half). Both halves keep the original block's
 * type and importance - the user re-tags them via the type picker instead of
 * typing. `newId` is generated by the caller so this stays pure/testable.
 * No-op if `id` isn't found or `lineIndex` doesn't fall strictly inside the
 * block's lines.
 */
export function splitBlockAtLine(blocks, id, lineIndex, newId) {
  const idx = blocks.findIndex((b) => b.id === id);
  if (idx === -1) return blocks;
  const lines = blocks[idx].content.split('\n');
  if (lineIndex <= 0 || lineIndex >= lines.length) return blocks;

  const first = { ...blocks[idx], content: lines.slice(0, lineIndex).join('\n') };
  const second = { ...blocks[idx], id: newId, content: lines.slice(lineIndex).join('\n') };
  const arr = [...blocks];
  arr.splice(idx, 1, first, second);
  return arr;
}

/** Moves the block with `id` by `direction` (-1 or 1) places, clamped to array bounds. */
export function moveBlock(blocks, id, direction) {
  const idx = blocks.findIndex((b) => b.id === id);
  if (idx === -1) return blocks;
  const to = idx + direction;
  if (to < 0 || to >= blocks.length) return blocks;
  const arr = [...blocks];
  [arr[idx], arr[to]] = [arr[to], arr[idx]];
  return arr;
}
